### ISSUE TITLE
Clarify configuration of routing: bin/kusabana or config.yml

### ISSUE THREAD

**Issue by suzuken** [voyagegroup/kusabana#79]
Both `bin/kusabana` and `config.yml` has a rule for routing like below: 

bin/kusabana

```
proxy = Kusabana::Proxy.new(config)
proxy.add_rule('/01a', rule)
proxy.add_rule('/01b', rule)
proxy.add_rule('/01c', rule)
proxy.start
```

config.yml

```
es:
  remotes:
    - path: '/01a'
      host: 'some-es-server01a'
      port: 9200

    - path: '/01b'
      host: 'some-es-server01b'
      port: 9200

    - path: '/01c'
      host: 'some-es-server01c'
      port: 9200
```

This occurs misunderstanding abount settings kusabana. Make it simple.
